backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/pages/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "project"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Goal", name: "goal", widget: "string"}
      - {label: "Role", name: "role", widget: "string"}
      - {label: "Resources", name: "resources", widget: "string"}
      - {label: "Order", name: "order", widget: "number", min: 1, max: 7, default: 1}
      - {label: "Image", name: "media", widget: "image"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        name: "home"
        label: "Home Page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Headshot", name: "headshot", widget: "image"}
